AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for Text-to-SQL Agent Knowledge Base'

Parameters:
  KnowledgeBaseName:
    Type: String
    Default: text-to-sql-kb
    Description: Name for the Bedrock Knowledge Base
  
  S3BucketName:
    Type: String
    Default: text-to-sql-kb-demo-2024
    Description: S3 bucket for knowledge base documents

Resources:
  # OpenSearch Serverless Collection
  OpenSearchCollection:
    Type: AWS::OpenSearchServerless::Collection
    Properties:
      Name: !Sub '${KnowledgeBaseName}-collection'
      Type: VECTORSEARCH
      Description: 'Vector collection for Text-to-SQL Knowledge Base'

  # OpenSearch Serverless Security Policy
  OpenSearchSecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub '${KnowledgeBaseName}-security-policy'
      Type: encryption
      Policy: !Sub |
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/${KnowledgeBaseName}-collection"]
            }
          ],
          "AWSOwnedKey": true
        }

  # OpenSearch Network Policy
  OpenSearchNetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub '${KnowledgeBaseName}-network-policy'
      Type: network
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/${KnowledgeBaseName}-collection"]
              },
              {
                "ResourceType": "dashboard",
                "Resource": ["collection/${KnowledgeBaseName}-collection"]
              }
            ],
            "AllowFromPublic": true
          }
        ]

  # OpenSearch Data Access Policy
  OpenSearchDataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: !Sub '${KnowledgeBaseName}-data-access-policy'
      Type: data
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/${KnowledgeBaseName}-collection"],
                "Permission": [
                  "aoss:CreateCollectionItems",
                  "aoss:DeleteCollectionItems",
                  "aoss:UpdateCollectionItems",
                  "aoss:DescribeCollectionItems"
                ]
              },
              {
                "ResourceType": "index",
                "Resource": ["index/${KnowledgeBaseName}-collection/*"],
                "Permission": [
                  "aoss:CreateIndex",
                  "aoss:DeleteIndex",
                  "aoss:UpdateIndex",
                  "aoss:DescribeIndex",
                  "aoss:ReadDocument",
                  "aoss:WriteDocument"
                ]
              }
            ],
            "Principal": [
              "arn:aws:iam::${AWS::AccountId}:role/BedrockKnowledgeBaseRole",
              "arn:aws:iam::${AWS::AccountId}:root"
            ]
          }
        ]

Outputs:
  OpenSearchCollectionArn:
    Description: 'ARN of the OpenSearch Serverless collection'
    Value: !GetAtt OpenSearchCollection.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OpenSearchCollectionArn'
  
  OpenSearchCollectionEndpoint:
    Description: 'Endpoint of the OpenSearch Serverless collection'
    Value: !GetAtt OpenSearchCollection.CollectionEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-OpenSearchCollectionEndpoint'
  
  S3BucketName:
    Description: 'S3 bucket for knowledge base documents'
    Value: !Ref S3BucketName
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'
